version: '3.8'

services:
  spring-boot-app:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/hotel_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    restart: unless-stopped
    depends_on:
      - mysql-db
    networks:
      - hotel-network

  mysql-db:
    image: mysql:8.0
    container_name: ace_hotel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3311:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - hotel-network

volumes:
  db_data:

networks:
  hotel-network:
    driver: bridge