spring:
  application:
    name: hotel-backend
  datasource:
    url: jdbc:mysql://localhost:3311/hotel_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  graphiql:
    endpoint: /graphql
    enabled: true
server:
  port: 8082
grpc:
  server:
    port: 9090 # Set your desired gRPC server port here
# Logging
logging:
  org.springframework.web: DEBUG

# Swagger
swagger:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
# CORS Configuration
cors:
  allowed-origins: http://localhost:5173

---
spring:
  profiles:
    active:
    - prod
  application:
    name: hotel-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  graphiql:
    endpoint: /graphql
    enabled: true
server:
  port: 8082
grpc:
  server:
    port: 9090
logging:
  org.springframework.web: DEBUG
swagger:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}